### ISSUE TITLE
about data format 

### ISSUE THREAD

**Issue by pengcheng-yan** [sefeoglu/RAG4RE#2]
When I process the data there is the following error reported:
Traceback (most recent call last):
  File "/usr/local/RAG4RE/RAG4RE-master/src/data_augmentation/embeddings/sentence_embeddings.py", line 76, in <module>
    embeddings = compute_sentence(data)
  File "/usr/local/RAG4RE/RAG4RE-master/src/data_augmentation/embeddings/sentence_embeddings.py", line 44, in compute_sentence
    sent = " ".join(line['tokens'])
KeyError: 'tokens'
check data format as follows:
[{"id": "61b3a5c8c9a882dcfcd2", "docid": "AFP_ENG_20070218.0019.LDC2009T13", "relation": "org:founded_by", "token": ["Tom", "Thabane", "resigned", "in", "October", "last", "year", "to", "form", "the", "All", "Basotho", "Convention", "-LRB-", "ABC", "-RRB-", ",", "crossing", "the", "floor", "with", "17", "members", "of", "parliament", ",", "causing", "constitutional", "monarch", "King", "Letsie", "III", "to", "dissolve", "parliament", "and", "call", "the", "snap", "election", "."], "subj_start": 10, "subj_end": 12, "obj_start": 0, "obj_end": 1, "subj_type": "ORGANIZATION", "obj_type": "PERSON", "stanford_pos": ["NNP", "NNP", "VBD", "IN", "NNP", "JJ", "NN", "TO", "VB", "DT", "DT", "NNP", "NNP", "-LRB-", "NNP", "-RRB-", ",", "VBG", "DT", "NN", "IN", "CD", "NNS", "IN", "NN", ",", "VBG", "JJ", "NN", "NNP", "NNP", "NNP", "TO", "VB", "NN", "CC", "VB", "DT", "NN", "NN", "."], 
Is there a problem with the format of my data, please?

**Comment by sefeoglu** [comment]
Hi, 
You can change the` KeyError: **'tokens'**` into `token`.
I formatted this as token, head, tail and relation.
