### ISSUE TITLE
semeval errors

### ISSUE THREAD

**Issue by JLC7** [sefeoglu/RAG4RE#4]
I am trying to run main.py with the semeval embeddings and files in the data/semeval folder. 

I am getting an error during this call to the semeval_format [function ](https://github.com/sefeoglu/RAG4RE/blob/master/src/data_augmentation/prompt_generation/prompt_generation.py#L136)

The 'similar_sentences' are dict keys instead of sentences. I think the code as is may be calling the semeval_format function incorrectly with the wrong number of variables when the prompt type is "rag". 

Also the 'labels' don't seem to be provided.

**Comment by sefeoglu** [comment]
Hi, 
I know this error :) The paper is still under review so, I could not update the master branch due to policy of Journal. You can use the [updates branch](https://github.com/sefeoglu/RAG4RE/tree/updates).
Thanks again

**Comment by JLC7** [comment]
Thanks for the update. I am still running into errors:
I replaced `relations_path=/Users/sefika/RAG4RE/data/tacred/rel2id.json`

with 

`relations_path=/data/semeval/original_data/relations.json`

But I get an error because 'relations' in the semeval_format function is `dict_keys(['sentence', 'relation'])`, I think I am pointing to the wrong relations.json file or misunderstand which json file the relations_path should be. I tried the other relation files under /dataset/semeval/original_data/ but they don't work. I am guessing labels should be the string names in the relations.json file? i.e

                "Cause-Effect(e1,e2)",
                "Cause-Effect(e2,e1)",
                "Component-Whole(e1,e2)",
                "Component-Whole(e2,e1)",
                "Content-Container(e1,e2)",
                "Content-Container(e2,e1)",
                "Entity-Destination(e1,e2)",
                "Entity-Destination(e2,e1)",
                "Entity-Origin(e1,e2)",
                "Entity-Origin(e2,e1)",
                "Instrument-Agency(e1,e2)",
                "Instrument-Agency(e2,e1)",
                "Member-Collection(e1,e2)",
                "Member-Collection(e2,e1)",
                "Message-Topic(e1,e2)",
                "Message-Topic(e2,e1)",
                "Product-Producer(e1,e2)",
                "Product-Producer(e2,e1)",
                "Other"

**Comment by sefeoglu** [comment]
Thanks for pointing out the issues about semeval.
I  fixed it in retriever part and updated the config.ini only for semeval rag prompt generation.

Best.
