### ISSUE TITLE
Question about RAG prompting

### ISSUE THREAD

**Issue by JLC7** [sefeoglu/RAG4RE#7]
I have a question about the RAG template for the prompt generation. For the example sentence (not the query one) do you include the ground truth relation for it as well? Looking at the code it seems like its just an example sentence without the relationship. Did you try it with the relation and see if that helped improve results? Thank you!

**Comment by sefeoglu** [comment]
I did not include ground truth relation there, since it would be one shot prompting. It is out of my work. However, you can try it as well.
